services:
  ionos-dyndns:
    image: philippluettecke/ionos-dyndns:latest
    container_name: ionos-dyndns
    restart: unless-stopped
    environment:
      - CRON_SCHEDULE=*/15 * * * *
      - TZ=Europe/Berlin
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    network_mode: host
    user: 1000:1000
networks: {}
